version: "3.7"
#Hay dos servicia "db" y "pgadmin"
services:
  #db corre postgres:12.2 desde DockerHub en un Contenedor
  db:
    image: postgres:12.2
    restart: always
    environment:
      POSTGRES_DB: postgresDB1
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      #La variable de entorno PGDATA se usa para configurar el servidor PostgreSQL para almacenar los datos en el directorio /var/lib/postgresql/data del contenedor.
      PGDATA: /var/lib/postgresql/data
    #el contenido del directorio /var/lib/postgresql/data se guardará de forma permanente en el volumen db-data .
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
 
  #pgadmin corre pgadmin desde dockerhub en otro contenedor
  pgadmin:
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@linuxhint.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    #odo el contenido del directorio /var/lib/pgadmin se guardará permanentemente en el volumen pgadmin-data .
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    #se crea un alias de nombre de host pgsql-server para el contenedor de base de datos
    #Por lo tanto, puede acceder al servidor PostgreSQL utilizando pgsql-server como nombre de host (no se requiere dirección IP).
    links:
      - "db:pgsql-server"
      
volumes:
  db-data:
  pgadmin-data: